title: "French conjugation"
description: "Learn French verb conjugations effortlessly! Daily updates, examples, and an app to improve your skills fast!"
keywords: "conjuga, conjuga app, french conjugation app, french verbs, learn french, french language"
email: contact@conjuga.app
timezone: UTC
baseurl: ""
permalink: "/:categories/:year/:month/:day/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: Conjuga
paginate: 30
disqus: 'conjuga'
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: weakly
feed_update_frequency: 2
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed


# Ensure this line is present:
url: "https://conjuga.app"

# Authors
authors:
  Conjuga:
    name: conjuga
    display_name: conjuga
    avatar: 'assets/images/logo.png'
    email: contact@conjuga.app
    form_endpoint: https://formspree.io/f/mdknkdew
    web: https://conjuga.app
    twitter: https://twitter.com/conjapp
    description: "Learn French verb conjugations effortlessly! Daily updates, examples, and an app to improve your skills fast!"


# Social
social:
  instagram: "https://www.instagram.com/conjuga.app/"
  facebook: "https://www.facebook.com/conjugapp"
  twitter: "https://x.com/conjapp"
  tiktok: "https://www.tiktok.com/@frenchconjugation"
  youtube: "https://www.youtube.com/@conjuga"

# App Store Url
appStore:
  url: "https://conjuga.app.link/VlkyCxUWOKb"

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives